# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
unless defined? VAGRANTFILE_API_VERSION
  VAGRANTFILE_API_VERSION = "2"
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Setup resource requirements
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end
  
  config.vm.box = "yungsang/boot2docker"

  # need a private network for NFS shares to work
  config.vm.network "private_network", ip: "192.168.50.4"

  # Rails Server Port Forwarding
  config.vm.network "forwarded_port", guest: 3000, host: 3000

  # Must use NFS for this otherwise rails
  # performance will be awful
  config.vm.synced_folder "../", "/var/www", type: "nfs"
end
